### ISSUE TITLE
any plans to complete package?

### ISSUE THREAD

**Issue by vtolstov** [pp-qq/rocksdb.go#1]
Hi! i found package and as i understand - it pure golang rocksdb, but i don't understand status, what it supports and how far from basic parity with leveldb?

**Comment by hidva** [comment]
rocksdb.go 确实是一个使用纯 golang 实现的 rocksdb, 预期是在文件格式与使用方式等方面与 rocksdb 完全兼容. 目前由于工作原因开发时间不固定所以并没有明确的开发计划. 

You can translate this message via  http://fanyi.baidu.com/.

Rocksdb.go is indeed a rocksdb implemented by pure golang. It is fully compatible with rocksdb in terms of file format and usage mode. At present, the development time is not fixed due to working reasons, so there is no definite development plan.
